In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
pd.set_option('max_columns', 100)
pd.set_option('max_rows', 100)

In [3]:
os.getcwd()

'/Users/alvastrand/Documents/OU/Research/notebooks'

In [4]:
path = '/Users/alvastrand/Documents/OU/Research/data/'
os.chdir(path)

In [5]:
os.getcwd()

'/Users/alvastrand/Documents/OU/Research/data'

In [6]:
subdir = 'output/'
filename = 'obligate_aerial_insectivores_birdlife_nacc_north_america.csv'
df_a_i = pd.read_csv(subdir + filename)

In [7]:
subdir = 'ebird/ebd_output/'
filename = 'ebird_taxonomy.csv'
df_e_t = pd.read_csv(subdir + filename)

In [8]:
print(len(df_a_i))
print(len(df_e_t))

19
16513

In [9]:
df_a_i.head(2)

,scientific_name,LON.b,LAT.b,LON.nb,LAT.nb,MAX.LAT.nb,distance,intersect,id,avibase id,rank,common_name,french_name,order,family,subfamily,genus,annotation,status_accidental,status_hawaiian,status_introduced,status_nonbreeding,status_extinct,status_misplaced
0,Antrostomus arizonae,-103.398915,24.849878,-100.202682,20.712022,28.631368,563.581341,0.625247,2061,CED2468C3EF9B42C,species,Mexican Whip-poor-will,Engoulevent d'Arizona,Caprimulgiformes,Caprimulgidae,Caprimulginae,Antrostomus,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Antrostomus carolinensis,-88.058904,34.063816,-83.140011,16.459749,30.354784,2011.374172,0.049623,718,8D3E887123F5C670,species,Chuck-will's-widow,Engoulevent de Caroline,Caprimulgiformes,Caprimulgidae,Caprimulginae,Antrostomus,Monotypic.,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_e_t.head(2)

,scientific_name,common_name,species_code,category,taxon_order,order,family,report_as
0,Struthio camelus,Common Ostrich,ostric2,species,1,Struthioniformes,Struthionidae,NaN
1,Struthio molybdophanes,Somali Ostrich,ostric3,species,6,Struthioniformes,Struthionidae,NaN

In [11]:
df_a_i_e_t = df_a_i[['scientific_name', 'common_name']].merge(df_e_t, on=['scientific_name', 'common_name'])

In [12]:
len(df_a_i_e_t)

19

In [13]:
df_a_i_e_t.head(2)

,scientific_name,common_name,species_code,category,taxon_order,order,family,report_as
0,Antrostomus arizonae,Mexican Whip-poor-will,souwpw1,species,3533,Caprimulgiformes,Caprimulgidae,NaN
1,Antrostomus carolinensis,Chuck-will's-widow,chwwid,species,3510,Caprimulgiformes,Caprimulgidae,NaN

In [14]:
df_a_i_e_t

,scientific_name,common_name,species_code,category,taxon_order,order,family,report_as
0,Antrostomus arizonae,Mexican Whip-poor-will,souwpw1,species,3533,Caprimulgiformes,Caprimulgidae,NaN
1,Antrostomus carolinensis,Chuck-will's-widow,chwwid,species,3510,Caprimulgiformes,Caprimulgidae,NaN
2,Antrostomus ridgwayi,Buff-collared Nightjar,bucnig,species,3528,Caprimulgiformes,Caprimulgidae,NaN
3,Antrostomus vociferus,Eastern Whip-poor-will,whip-p1,species,3531,Caprimulgiformes,Caprimulgidae,NaN
4,Chordeiles acutipennis,Lesser Nighthawk,lesnig,species,3400,Caprimulgiformes,Caprimulgidae,NaN
5,Chordeiles minor,Common Nighthawk,comnig,species,3408,Caprimulgiformes,Caprimulgidae,NaN
6,Phalaenoptilus nuttallii,Common Poorwill,compoo,species,3504,Caprimulgiformes,Caprimulgidae,NaN
7,Aeronautes saxatalis,White-throated Swift,whtswi,species,4030,Caprimulgiformes,Apodidae,NaN
8,Chaetura pelagica,Chimney Swift,chiswi,species,3755,Caprimulgiformes,Apodidae,NaN
9,Chaetura vauxi,Vaux's Swift,vauswi,species,3756,Caprimulgiformes,Apodidae,NaN
10,Cypseloides niger,Black Swift,blkswi,species,3702,Caprimulgiformes,Apodidae,NaN
11,Hirundo rustica,Barn Swallow,barswa,species,23153,Passeriformes,Hirundinidae,NaN
12,Petrochelidon fulva,Cave Swallow,cavswa,species,23252,Passeriformes,Hirundinidae,NaN
13,Petrochelidon pyrrhonota,Cliff Swallow,cliswa,species,23244,Passeriformes,Hirundinidae,NaN
14,Progne subis,Purple Martin,purmar,species,23051,Passeriformes,Hirundinidae,NaN
15,Riparia riparia,Bank Swallow,banswa,species,23105,Passeriformes,Hirundinidae,NaN
16,Stelgidopteryx serripennis,Northern Rough-winged Swallow,nrwswa,species,23036,Passeriformes,Hirundinidae,NaN
17,Tachycineta bicolor,Tree Swallow,treswa,species,23074,Passeriformes,Hirundinidae,NaN
18,Tachycineta thalassina,Violet-green Swallow,vigswa,species,23084,Passeriformes,Hirundinidae,NaN

In [ ]:
subdir = 'output/'
filename = 'obligate_aerial_insectivores_ebird_species_codes.csv'
# df_a_i_e_t.to_csv(subdir + filename, index=False)